#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config normal_border_color \#81a1c1
bspc config focused_border_color \#d8dee9
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config top_padding 20

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr

fcitx5 &

feh --bg-scale ~/Pictures/backgrounds/tower-nord.png

dunst &

~/.config/polybar/launch.sh dark &

picom -b &
